In [2]:
import torch

print("Versión de PyTorch:", torch.__version__)

# 1. Un tensor 1D → como una fila de casillas
x = torch.tensor([1, 2, 3])
print("Vector:", x, "| shape:", x.shape)

# 2. Una radiografía en blanco y negro → tensor 2D (alto x ancho de píxeles)
radiografia = torch.rand(5, 5)  # 5x5 píxeles con valores random entre 0 y 1
print("Radiografía simulada:\n", radiografia)


Versión de PyTorch: 2.14.0+cpu
Vector: tensor([1, 2, 3]) | shape: torch.Size([3])
Radiografía simulada:
 tensor([[0.5354, 0.5987, 0.6449, 0.4911, 0.7051],
        [0.6616, 0.6843, 0.1624, 0.9693, 0.4205],
        [0.5459, 0.0061, 0.8013, 0.3712, 0.8496],
        [0.4019, 0.0572, 0.0100, 0.3792, 0.7316],
        [0.6301, 0.5674, 0.6907, 0.8659, 0.2243]])


In [4]:
# Suma y multiplicación entre tensores
a = torch.rand(3, 3)
b = torch.rand(3, 3)

suma = a + b
producto = a * b          # multiplicación elemento por elemento
producto_matricial = a @ b  # multiplicación matricial real (como en álgebra lineal)

print("Suma:\n", suma)
print("Producto elemento a elemento:\n", producto)
print("Producto matricial:\n", producto_matricial)

# Reshape: cambiar la forma sin cambiar los datos
x = torch.rand(6)
print("Original:", x.shape)
print("Reacomodado a 2x3:", x.reshape(2, 3).shape)

Suma:
 tensor([[1.0690, 1.0631, 1.4756],
        [0.3518, 1.0940, 1.0238],
        [1.6376, 1.8114, 1.2657]])
Producto elemento a elemento:
 tensor([[0.1780, 0.0744, 0.4909],
        [0.0144, 0.2252, 0.1537],
        [0.6604, 0.8203, 0.3186]])
Producto matricial:
 tensor([[0.9443, 0.7962, 1.1921],
        [1.0320, 0.9919, 0.4870],
        [1.2681, 1.1365, 1.1804]])
Original: torch.Size([6])
Reacomodado a 2x3: torch.Size([2, 3])


In [6]:
x = torch.rand(3, 2)
y = torch.ones(x.size())
z = x + y

print(z)
print(z[0])       # primera fila
print(z[:, 1:])   # todas las filas, desde la columna 1 en adelante

# Operación normal: crea un tensor NUEVO, no toca el original
z.add(1)
print("z sigue igual:\n", z)

# Operación in-place (con guion bajo _): SÍ modifica z directamente
z.add_(1)
print("z ya cambió:\n", z)

tensor([[1.5048, 1.3065],
        [1.2952, 1.9677],
        [1.2222, 1.6598]])
tensor([1.5048, 1.3065])
tensor([[1.3065],
        [1.9677],
        [1.6598]])
z sigue igual:
 tensor([[1.5048, 1.3065],
        [1.2952, 1.9677],
        [1.2222, 1.6598]])
z ya cambió:
 tensor([[2.5048, 2.3065],
        [2.2952, 2.9677],
        [2.2222, 2.6598]])


In [ ]:
import numpy as np

a = np.random.rand(4, 3)
b = torch.from_numpy(a)   # de numpy a tensor
print(b)

de_vuelta = b.numpy()     # de tensor a numpy
print(de_vuelta)

#comparten la misma memoria
b.mul_(2)   # multiplico el tensor por 2, in-place
print(a)    # array numpy cambio

tensor([[0.0230, 0.0425, 0.4467],
        [0.3181, 0.8391, 0.8389],
        [0.7756, 0.6637, 0.3864],
        [0.0220, 0.5305, 0.5756]], dtype=torch.float64)
[[0.02300887 0.04253272 0.44665156]
 [0.31807742 0.83906814 0.8388604 ]
 [0.77563378 0.66373545 0.38638476]
 [0.02200948 0.53046705 0.57555116]]
[[0.04601773 0.08506544 0.89330312]
 [0.63615484 1.67813628 1.6777208 ]
 [1.55126756 1.32747089 0.77276952]
 [0.04401896 1.06093411 1.15110233]]
